### ISSUE TITLE
Limite errado parte de buscar transactions

### ISSUE THREAD

**Issue by ViniciusCestarii** [Edmar-Sousa/rinha-backend-2024q1#1]
Olá, Achei uma parte do seu código que não bate os requerimentos da rinha no arquivo app/Controller/TransactionController.php onde o limit do get do histórico de transações deveria ser 10, mas está 5.

        $transactions = Db::table('transactions')
            ->where('client_id', $clientId)
            ->select([ 
                'value',
                'type',
                'description',
                'created_at',
            ])
            ->orderByDesc('created_at')
            ->limit(5) // deveria ser 10
            ->get();

Nessa [parte ](https://github.com/zanfranceschi/rinha-de-backend-2024-q1?tab=readme-ov-file#extrato) diz que ultimas_transacoes é uma lista ordenada por data/hora das transações de forma decrescente contendo até as 10 últimas transações

**Comment by Edmar-Sousa** [comment]
Obrigado! Fiz a correção do erro.
